---
title: "1: Observe and Interact"
format:
  html:
    toc: true
---

#### Consider what you see in the environment around you

#### *"By taking the time to engage with nature we can design solutions that suit our particular situation"*

## 🌳 About the Principle

This principle is about investigating and opening to our capacity to observe the world around us and to pay attention to what is true with compassion, honesty and as much clarity as we can muster. It asks us to watch what we do and how we interact with others without judgement before we take any action.

This calls us to investigate what actually occurs in our life instead of what we imagine should happen. It can be eye opening

This is sometimes hard to do in our own life because it's like trying to tickle ourselves. How can we see ourselves and notice what is happening in our daily life?

A few ways to think about it occur to me. First is that we can look at what we complain about. When we complain or have feelings of annoyance or anxiety it can often mean there's something that is meaningful to us. If we listen to what is behind the complaint, it might help us to determine what it is that we really want.

We might also consider asking others to help us with this task. What do THEY see when they come into our spaces, or ask us about our lives? How might we ask others to help us see our lives more fully? What do they notice when they walk into the garden that is our daily life? What mood do they find us in? What do they see in our appearance? Our areas of interest?

## Observing Your Life

These questions are a starting point for ways you might inquire about your life right now, but idea isn't necessarily for you to answer every one of them, rather it's about taking some time to notice what is happening.

One starting place is to consider the aspects of your life and consider each separately. What do you notice about each of these aspects of modern living?

-   Health and Well-Being
-   Work and Career
-   Relationships with Friends and Family
-   Personal Growth and Learning
-   Finances and Financial Health
-   Home and Living Environment
-   Community
-   Play, Leisure and Creativity
-   Spirituality and Meaning

Looking at these attributes, which seem the most important to you right now? Where do you feel you're satisfied? Where do you want things to shift? What seems exciting? What seems concerning?

-   What are the things you want to show others about your life? What is easy to see and to share with others? What things are less appealing to share with others about your life?

-   If someone you didn't know were to come and watch your daily life from the outside, what might they say about you? What would they see?

-   What might a trusted friend or family member say about how you're doing right now?

-   What does your home/living space look like right now? What might someone say about your space if they were to walk into it without you there? What might they notice about what is important to you?

-   What varies in your life based on the time of day? Are there certain times of day when your mood worsens or improves?

-   How do I speak about my life? What words am I using to describe my state of being? What do I say when someone asks "How are you?"

## Observing in Your Community

-   What is the collective mood right now? What are the ongoing topics of conversation? What do people want to talk about?

-   What are the changes we've seen recently? Are there changes in the spaces around us? The weather? The season? The politics? The mood?

-   What words and language are people using to talk about big issues right now? How are they speaking about the past? The future?

## Examples in the Natural World

We can look to almost every system in the natural world to find examples of observation before interaction.

-   **Seasonal Changes -** As the seasons change we see plants and animals behaving differently. In the fall, trees shed their leaves, conserve energy in the winter and then bud and flower in the spring. Animals behave differently too, from hoarding food to hibernation in the winter.
-   **Predators Watching Prey -** Animals that rely on other animals as food or who are seen as food are likely to know instinctively how to respond to the movements of another animal.
-   **Phototropism** - Plants "watch" for the light and grow towards it. Consider a field of sunflowers that follows the sun, or trees that reach higher to get more light for their leaves.
-   **Migration** - Animals that move based on the temperature, light and food availability are responding to the things they sense and experience in their world.
-   **Weather** - We could think of weather patterns as responding to the environmental conditions such as temperature, wind patterns or humidity to make clouds or move storms.

## Integrating this Principle

-   Walk into a room in your house and look around, attempt to see the room with beginner eyes. Given what you see, where do you think people spend their time? What are they doing? What matters to them?

-   Spend some time watching something that occurs in the natural environment around your hom. What is that bug doing on that tree? How is the neighborhood cat moving in the backyard? When does the crow make noises? What do the clouds look like? How does the light change in your room?

## Resources for Further Exploration

-   [Permaculture Principles.com on Principle 1](https://permacultureprinciples.com/permaculture-principles/_1/)
-   Herman, Amy E. Visual Intelligence: Sharpen Your Perception, Change Your Life. Reprint edition. Carol Stream: HarperOne, 2017.
-   Walker, Rob. The Art of Noticing: 131 Ways to Spark Creativity, Find Inspiration, and Discover Joy in the Everyday. Knopf, 2019.
