---
title: "3: Obtain a Yield"
format:
  html:
    toc: true
---

#### Obtain a Yield 

#### *"Ensure that you are getting truly useful rewards as part of the work that you are doing."* 

#### 

## 🧺 About the Principle

This principle suggests that what we grow and cultivate in our lives should offer us a yield or a benefit and that we should set ourselves up so that the things we do have multiple and perhaps even multiplicative benefits. This principle is as much about looking for the benefits as it is about making sure that the benefits are there for all.

I’ve heard that some people who are devoted to permaculture will only grow things in their gardens that have multiple uses. For instance, one might grow bamboo which offers a variety of yields: it creates shade, it’s a privacy fence, it stops water from flowing down a hill and it can be used to make things.

What I appreciate about this way of thinking is that it offers us a variety of ways to consider benefits in doing what we do. For example, we might look at the work we do and think mostly of its benefits in terms of money, status or health insurance. But using this principle asks us to broaden the benefit of doing this job to consider more things. Does this job offer me a sense of meaning? The ability to be in relationship with people I enjoy? The capacity to learn new things? The capacity to provide for my family?

## Yield in Your Life 

-   What is it that I have an easy time yielding? What do I have a LOT of?

-   Of the things that I have an abundance of, what do feel glad to have so much of?

    -   How might I share the excess?

    -   What would I prefer to have less of?

-   What is it that I struggle to cultivate? What do I not have enough of?

    -   What do I not cultivate that I’m glad to keep out of my life?

    -   What do I not cultivate that I wish I had more of?

## Yield in Your Community

-   What does your community have a lot of? What does it lack?

-   Where could trade happen to increase the overall community yield? What do I have that you might need? What do you have that I might need? Where might we create multiple wins for the different community members?

## Examples in the Natural World 

-   **Fruit Trees** - Fruit trees are fantastic examples. They offer shade, fruit to nourish, a home for birds and insects . As trees they improve the air and offer leaves to the soil. When their life is over, they offer wood for burning or for building.

-   **Compost -** This natural process is a way of turning foodscraps, yard waste and other debris into rich beneficial material for gardens.

-   **Pollinator Gardens** - Planting flowers that bring birds, bees, butterflies and hummingbirds into your garden gives us beautiful spaces, but also creates pollination - a necessity for food and for the growth of many plants.

## Integrating this Principle

-   This principle is ideally considered with other principles as you might think of it as something that encourages you to increase the amount of things you have. But another way to think about it is in terms of mutual benefit and making sure that the yields we have are working for our lives. Take some time to think about what you already have in abundance, to think through the places you already have a high yield. Then consider the places where less of a yield is apparent to you.

## Resources for Further Exploration 

-   [Permaculture Principles.com Principle 3](https://permacultureprinciples.com/permaculture-principles/_3/)
