---
title: "Principle 4: Apply Self-Regulation and Accept Feedback"
author: "Beth M. Duckles"
format:
  html:
    toc: true
---

The idea for this principle is to consider and be open to accepting feedback. Our natural world has many feedback mechanisms built into it, and we are seeing that right now in global challenges like climate change.

This principle urges us to consider how to evaluate and to respond to the feedback we get so that we are not stuck continuing to do things without evaluating how beneficial they are for ourselves and for others in our lives.

-   Where are the formal feedback loops in my life? Do I get grades? Progress reports? Temperature readings? Scales? Lab Tests? Blood Tests? Deadlines? Performance Metrics? Evaluations? Comments? What impact do these have on me? How do I respond to them?

-   What kinds of informal feedback loops do I have in my life? How do people respond to me socially? What do people say when they talk about me or my work? What feedback do they give me?

-   What is my typical response to feedback? Do I ignore it? Take it seriously? Does it depend on who or how I get that feedback? When do I respond and when do I not respond?

-   What activities occur in my life that I respond to without thinking? Am I responsive to the weather? The news? My partner’s mood? The dog’s appetite? The day of the week? The terrain of my backyard?
