---
title: "6: Produce No Waste"
format:
  html:
    toc: true
---

#### Produce No Waste

#### *"By valuing and making use of all the resources that are available to us, nothing goes to waste."*

## 🗑️ About the Principle

I like to think of a “closed loop” system as like a dome on Mars or the Moon. Everything has to stay in the dome, which means that waste has to be dealt with. Waste has to offer something to the rest of the system otherwise we’ll have a dome overflowing with stuff we don’t want.

This principle suggests that what we “waste” is something to value. Manure for instance is a remarkable fertilizer and serves a purpose in a garden. We wouldn’t call that waste even though it is excrement. William McDonough's idea of Cradle to Cradle Manufacturing asks us to think about waste not as something bad, but as something that can be a raw material for something else.

This principle seeks to question our modern concept of waste and to suggest that we see all that we create and produce as useful. When we look at our lives and what we spend our time, resources and energy doing things, where are we creating waste?

## No Waste in Your Life

-   Where do I think of myself as wasting time? Where do I waste energy or effort? Where do I waste money?

    -   What would it look like to recast some of these "wastes" as nourishing something? Perhaps staring out the window allows our imagination to soar. Perhaps extra energy expended is a chance to learn our limits. Perhaps money expenses are opportunities for money to flow in new directions.

-   What is the difference between something that is wasteful and something that yields things I might not like (such as weeds)?

-   What piles up in my life? What do I lose? What do I forget?

-   What in my life could be maintained and cared for with more attention? What would it look like to care for what I already have?

## No Waste in Your Community

-   What do we do with "wasted" space in our community?

-   How do we

-   What might be fertilized by

## Examples in the Natural World 

## Integrating this Principle

-   There is a principle from Bill McDonough around the idea of Waste = Food.

## Resources for Further Exploration

-   

-   Waste = Food or [Cradle to Cradle Manufacturing from William McDonough](https://mcdonough.com/cradle-to-cradle/)
