---
title: "12: Creatively Use and Respond to Change"
format:
  html:
    toc: true
---

#### Creatively Use and Respond to Change

#### *"We can have a positive impact on inevitable change by carefully observing, and then intervening at the right time."*

## 🦋 About the Principle

The last principle reminds us that change is a constant and we are going to have to keep responding to an evolving world. Even if we are doing everything “right” there will always be things to adapt to. I find this incredibly inspiring because it reminds us that while change is uncomfortable, it's not a bad thing.

There's a publication called Oldster that allows folks of any age to contribute with the idea that we are all as old as we've ever been. I really enjoy this framing of what it means to get older as it includes us all in the idea of changing and shifting to meet the place that we are living in now.

There are places where we’re already changing. As we get older and our loved ones get older too. We can use this principle to cultivate a flexible and creative response to those changes. 

## Responding to Change in Your Life

-   Where am I facing shifts and changes in my life? Where am I resistant to change? Where am I excited about change?

-   Where can I be more creative and intentional in the things that are shifting in my life? Where can I bring my skills, abilities and resources to bear on what is shifting?

-   In what circumstances is it easy for me to be flexible and to adapt to change? In what circumstances is it harder for me to be flexible and adapt to change?

## Responding to Change in Your Community

-   How is my community changing? What are the big changes? The smaller and more subtle changes?

-   What changes have felt easy to accept and what changes are harder to accept? How are we responding to the changes we have as a group?

## Examples in the Natural World

-   **Seasons** - Spring, Summer, Fall and Winter - these are the seasons we think of but perhaps each location has smaller seasons that are specific to your area. What time of year are certain flowers likely to bloom? When do the leaves change? When is the air crisp? Noticing the seasons in your area may be more specific than the categories we typically think of.

-   **Time of day -** As the sun moves through different parts of the day, the light is different and the weather shifts too.

-   **Moon Cycles -** We may not always be aware of the moon cycles, but if we spend a bit of time paying attention, what might we notice about the tides, the amount of light we see at night?

## Integrating this Principle

-   Noticing the changes and sitting with them is a starting place for working with change. Perhaps if this hard, noticing where the changes we notice are challenging for us and where we welcome the changes.

## Resources for Further Exploration

-   [PermaculturePrinciples.com - Principle 12](https://permacultureprinciples.com/permaculture-principles/_12/)
